# serverless.yml

service: weddingRSVP

provider:
  name: aws
  apiKeys:
    - primary
  runtime: nodejs8.10
  stage: dev
  region: us-east-2

functions:
  app:
    handler: app.server # reference the file and exported method
    events: # events trigger lambda functions
      # - http: # this is an API Gateway HTTP event trigger
      #     path: /
      #     method: ANY
      #     cors: true
      #     private: true
      # - http: # all routes get proxied to the Express router
      #     path: /{proxy+}
      #     method: ANY
      #     cors: true
      #     private: true
      - http:
          path: cards/create
          method: post
          cors:
            origin: 'http://localhost:3000'
            headers:
             - Content-Type
             - X-Amz-Date
             - Authorization
             - X-Api-Key
             - X-Amz-Security-Token
             - X-Amz-User-Agent
             - Access-Control-Allow-Headers
             - Access-Control-Allow-Origin
             - Access-Control-Allow-Credentials
            allowCredentials: true
          # private: true
      - http:
          path: cards/{code}
          method: get
          cors:
            origin: 'http://localhost:3000'
            headers:
             - Content-Type
             - X-Amz-Date
             - Authorization
             - X-Api-Key
             - X-Amz-Security-Token
             - X-Amz-User-Agent
             - Access-Control-Allow-Headers
             - Access-Control-Allow-Origin
             - Access-Control-Allow-Credentials
            allowCredentials: true
          # private: true
      - http:
          path: cards/
          method: get
          cors:
            origin: 'http://localhost:3000'
            headers:
             - Content-Type
             - X-Amz-Date
             - Authorization
             - X-Api-Key
             - X-Amz-Security-Token
             - X-Amz-User-Agent
             - Access-Control-Allow-Headers
             - Access-Control-Allow-Origin
             - Access-Control-Allow-Credentials
            allowCredentials: true
          # private: true
      - http:
          path: cards/update/{code}
          method: put
          cors:
            origin: 'http://localhost:3000'
            headers:
             - Content-Type
             - X-Amz-Date
             - Authorization
             - X-Api-Key
             - X-Amz-Security-Token
             - X-Amz-User-Agent
             - Access-Control-Allow-Headers
             - Access-Control-Allow-Origin
             - Access-Control-Allow-Credentials
            allowCredentials: true
          # private: true